import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/navbar/page'
import Footer from './footer/page'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Madhav Goyal PortFolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'/>
      {/* <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossOrigin="anonymous"></link> */}
      </head>
    
      <body className={inter.className}>
      <Navbar/>
        {children} 
     
     <Footer/>
     {/* <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossOrigin="anonymous"></script> */}
      </body>
    </html>
  )
}
